### PR TITLE
Update to Hyper 0.10 and Serde 0.9.

### PR DESCRIPTION
**Pull request by jimmycuadra**
Work in progress. The HTTPS test is failing, but I'm not sure why yet. Unclear if the client is failing to verify the server's cert, or the server is failing to verify the client's cert. I'm also not happy with having to change the API for supplying a client TLS credentials (native-tls only supports PKCS #12), but maybe this API is actually better.

### CODE REVIEW

**Comment by commandline** [comment]
Looks like the openssl error code may have to do with the ca cert. I will keep digging as I'd love to see a newer release with these changes. Do you happen to know if the updates will bring the openssl peer dependency up to date with 0.9.x? I want to use this in a project where I am also using medallion but get an error about mismatched openssl versions.

**Comment by commandline** [comment]
I used etcdctl to do an `ls` against your container use https. (I had to add a port line to `docker-compose.yml`.) I see this:
```
Error:  x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs
```
I will continue to dig...

**Comment by commandline** [comment]
OK, found this in a discussion around a different tool, logstash, but it seems like a way forward to try to resolve this: http://serverfault.com/a/611121

**Comment by commandline** [comment]
Sorry to keep adding then deleting comments, catching up on what is going in this PR. Do you need a password in some form to go along with the pkcs12 key and trust material? If I `openssl pkcs12 -in client.pfx`, it wants a password.

**Comment by commandline** [comment]
Again, sorry for all the comments that I then delete. This is a head scratcher.

**Comment by commandline** [comment]
Agreed, I definitely feel like I wasn't apply to add much, beyond confirm that the most obvious things aren't causing the failure. I'll compare against master to answer some other questions I have but I am curious if you have scripts or documentation you used to generate all the keys and certs the tests use. It certainly seems possible there is some subtle issue with the CA cert or the chain encoded into the PKCS12 file.

**Comment by jimmycuadra** [comment]
@commandline I just pushed a commit that automates the creation of all the certs and keys with Make. After you pull down the latest changes, run `make clean` to make sure you have an empty tests/ssl directory, then run `make` to regenerate them and drop you back into the container with rustc/cargo.

**Comment by commandline** [comment]
I think the volumes stanza in the docker-compose.yml is now clobber the pem files. I took out that stanza and the tests got passed a failure finding the client cert. Still not working, still looking.

**Comment by commandline** [comment]
```
root@b3f6e94c562c:/source# ls -l tests/ssl/
total 16
drwxr-xr-x 2 root root 4096 May  1 19:54 ca.pem
-rw-rw-r-- 1 1000 1000  258 Mar 15 16:43 openssl.cnf
drwxr-xr-x 2 root root 4096 May  1 19:54 server-key.pem
drwxr-xr-x 2 root root 4096 May  1 19:54 server.pem
root@b3f6e94c562c:/source# 
```

**Comment by commandline** [comment]
Changed the etcdsecure: stanza and now that container comes up and I can reproduce the original error:
```
  etcdsecure:
    image: quay.io/coreos/etcd:v2.3.7
    command: -advertise-client-urls=https://0.0.0.0:2379 -listen-client-urls=https://0.0.0.0:2379 -trusted-ca-file=/opt/ssl/ca.pem -cert-file=/opt/ssl/server.pem -key-file=/opt/ssl/server-key.pem -client-cert-auth
    volumes:
      - ./tests/ssl:/opt/ssl
```

**Comment by commandline** [comment]
It looks like the native-tls crate updated to 0.1.2 and added a way to specify the ca cert. I ran cargo update on this branch and saw that crate update to 0.1.2. I am going to try to add in the ca cert and see if that resolves the issue.

**Comment by commandline** [comment]
I got the https with client cert to pass! It was indeed the need for the CA certificate. You'll need to updated your Makefile to generate a DER formatted version of the CA cert: `openssl x509 -outform der -in certificatename.pem -out certificatename.der`.

I can try to generate a patch file, if you like. I am still seeing a failure but I think it is just some documentation tests or something that needs updating.

**Comment by commandline** [comment]
A patch ready to apply that will get the failing https test passing.

[0001-Add-CA-cert-into-client-config.zip](https://github.com/jimmycuadra/rust-etcd/files/968798/0001-Add-CA-cert-into-client-config.zip)

Up to updating to serde 1.0 while we are at it?

**Comment by jimmycuadra** [comment]
Awesome, thank you! I'll finish this out soon, and yes, I'll update to serde 1.0.

**Pull request merged**
